/**
 * !!! DON'T MODIFY THIS FILE !!!
 * It was generated by the script :
 *
 * `npx gql-fragments ./src/server/datamodel/dataModel.js`
 *
 * Or :
 *
 * `node ./node_modules/@mnemotix/weever-core/bin/generateGqlFragments.js ./src/server/datamodel/dataModel.js`
 *
 *
 * You may experiment that following error if you work with `yarn link @mnemotix/weever-core` in dev.
 *
 * "Cannot use GraphQLScalarType "Float" from another module or realm."
 *
 * See that solution to workarround : https://stackoverflow.com/questions/62356525/yarn-link-importing-graphql-js-project-into-another-graphql-js-project-showing
 */

export const gqlFragments = {
  __schema: {
    types: [
      {
        kind: "INTERFACE",
        name: "EntityInterface",
        possibleTypes: [
          {
            name: "AccessPolicy"
          },
          {
            name: "UserAccount"
          },
          {
            name: "Person"
          },
          {
            name: "ExternalLink"
          },
          {
            name: "Tagging"
          },
          {
            name: "Comment"
          },
          {
            name: "Concept"
          },
          {
            name: "Scheme"
          },
          {
            name: "Collection"
          },
          {
            name: "Vocabulary"
          },
          {
            name: "EmailAccount"
          },
          {
            name: "Phone"
          },
          {
            name: "Address"
          },
          {
            name: "Affiliation"
          },
          {
            name: "Organization"
          },
          {
            name: "Involvement"
          },
          {
            name: "ProjectContribution"
          },
          {
            name: "Project"
          },
          {
            name: "UserGroup"
          },
          {
            name: "Attachment"
          },
          {
            name: "Location"
          },
          {
            name: "GroupMembership"
          },
          {
            name: "Partnership"
          },
          {
            name: "File"
          },
          {
            name: "Point"
          },
          {
            name: "Creation"
          },
          {
            name: "Deletion"
          },
          {
            name: "Update"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "ActionInterface",
        possibleTypes: [
          {
            name: "Creation"
          },
          {
            name: "Deletion"
          },
          {
            name: "Update"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "AccessPolicyTargetInterface",
        possibleTypes: [
          {
            name: "UserAccount"
          },
          {
            name: "UserGroup"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "AgentInterface",
        possibleTypes: [
          {
            name: "Person"
          },
          {
            name: "Organization"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "OnlineContributionInterface",
        possibleTypes: [
          {
            name: "Tagging"
          },
          {
            name: "Comment"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "InstantInterface",
        possibleTypes: [
          {
            name: "Tagging"
          },
          {
            name: "Comment"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "SKOSElementInterface",
        possibleTypes: [
          {
            name: "Concept"
          },
          {
            name: "Scheme"
          },
          {
            name: "Collection"
          },
          {
            name: "Vocabulary"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "LocationInterface",
        possibleTypes: [
          {
            name: "Address"
          },
          {
            name: "Location"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "GeometryInterface",
        possibleTypes: [
          {
            name: "Point"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "SpatialEntityInterface",
        possibleTypes: [
          {
            name: "Address"
          },
          {
            name: "Location"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "DurationInterface",
        possibleTypes: [
          {
            name: "Affiliation"
          },
          {
            name: "ProjectContribution"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "OrganizationInterface",
        possibleTypes: [
          {
            name: "Organization"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "ResourceInterface",
        possibleTypes: [
          {
            name: "File"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "PersonInterface",
        possibleTypes: [
          {
            name: "Person"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "AccessPriviledgeInterface",
        possibleTypes: [
          {
            name: "ReadPriviledge"
          },
          {
            name: "WritePriviledge"
          }
        ]
      },
      {
        kind: "INTERFACE",
        name: "GroupInterface",
        possibleTypes: []
      },
      {
        kind: "INTERFACE",
        name: "ProjectOutputInterface",
        possibleTypes: []
      },
      {
        kind: "INTERFACE",
        name: "TemporalEntityInterface",
        possibleTypes: []
      },
      {
        kind: "INTERFACE",
        name: "MaterialEntityInterface",
        possibleTypes: []
      }
    ]
  }
};
