version: '2.1'

services:
  keycloak:
    image: jboss/keycloak:6.0.1
    container_name: ${COMPOSE_PROJECT_NAME}-sso
   # command: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/realm.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING "
    ports:
      - "8181:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ${DATA_PATH}/keycloak/realm.json:/tmp/realm.json
      -  ${DATA_PATH}/keycloak/data:/opt/jboss/keycloak/standalone/data
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_IMPORT=/tmp/realm.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 10s
      retries: 100
    networks:
      - oep

networks:
  oep:
    driver: bridge
