export const ROUTES = {
  INDEX: "/",
  PROFILE: "/profil",
  PROJECT: "/projet",
  MARKET: "/marché",
  INCOMES: "/salaires",
  SKILLS: "/compétences",
  TRAININGS: "/formations",
  TRANSPORTS: "/transport-et-logement",
  LIFE_STYLE: "/cadre-de-vie",
  SIGN_IN: "/",
  SIGN_UP: "/création-compte",
  PROFIL_EDIT: "/profil/edit",
  PASSWORD_FORGOTTEN: "/mot-de-passe-oublié",
  CARTONET_EDIT_EXPERIENCE: "/cartonet/edit-experience/:id?",
  CARTONET_EDIT_TRAINING: "/cartonet/edit-training/:id?",
  CARTONET_EDIT_HOBBY: "/cartonet/edit-hobby/:id?",
  CARTONET_EDIT_APTITUDES: "/cartonet/edit-aptitudes",
  CARTONET_SHOW_PROFILE: "/cartonet/show-profile",
  CARTONET_SHOW_JOBS: "/cartonet/show-jobs",
  CARTONET_SHOW_WISHED_JOBS: "/cartonet/show-wished-jobs",
  CARTONET_EXTRACT_SKILLS_FROM_CV: "/cartonet/extract-skills-from-cv",
  CARTONET_PRINT_PROFILE: "/cartonet/print",
};
